using Pkg
Pkg.add("SparseArrays")
Pkg.add("LinearAlgebra")
Pkg.add("ITensors")
Pkg.add("ITensorMPS")
Pkg.add("ProgressBars")
Pkg.add("KrylovKit")
Pkg.add("Plots")
Pkg.add("LaTeXStrings")
Pkg.add("ClassicalOrthogonalPolynomials")
Pkg.add("Random")
Pkg.add("PlotlyJS")